// <auto-generated />
using System;
using Diyalo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diyalo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414103602_AddProgramCategory")]
    partial class AddProgramCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diyalo.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$p3udSULwRe/31khdZJjp4uLWcdeK21zdj/DJMl6XZ0x0RHfZ4snDi",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Diyalo.Api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Diyalo.Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Diyalo.Api.Models.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Fill out our online application form on the Apply Now page. Our team will review your application and get back to you within 3-5 business days.",
                            IsVisible = true,
                            Order = 1,
                            Question = "How do I apply to volunteer?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "The minimum age is 18 years old for most programs.",
                            IsVisible = true,
                            Order = 2,
                            Question = "What is the minimum age to volunteer?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "We offer flexible durations from 2 weeks to 3 months.",
                            IsVisible = true,
                            Order = 3,
                            Question = "How long can I volunteer?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "The fee includes accommodation, meals, airport pickup, orientation, program placement, 24/7 local support, and a certificate of completion.",
                            IsVisible = true,
                            Order = 4,
                            Question = "What is included in the program fee?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "No, English is widely spoken in our programs.",
                            IsVisible = true,
                            Order = 5,
                            Question = "Do I need to speak Nepali?"
                        });
                });

            modelBuilder.Entity("Diyalo.Api.Models.HeroSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Highlight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeroSlides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Volunteer in Nepal",
                            Highlight = "Change a Life.",
                            IsVisible = true,
                            Order = 1,
                            Subtitle = "Diyalo connects passionate volunteers with communities that need them most.",
                            Title = "Light the Way."
                        },
                        new
                        {
                            Id = 2,
                            Badge = "Make an Impact",
                            Highlight = "Nepal.",
                            IsVisible = true,
                            Order = 2,
                            Subtitle = "Join our construction and community development programs across Nepal.",
                            Title = "Help Rebuild"
                        },
                        new
                        {
                            Id = 3,
                            Badge = "Teach & Inspire",
                            Highlight = "Shape the Future.",
                            IsVisible = true,
                            Order = 3,
                            Subtitle = "Volunteer as a teacher and give children the gift of education.",
                            Title = "Educate a Child."
                        });
                });

            modelBuilder.Entity("Diyalo.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVisible = true,
                            Label = "Home",
                            Order = 1,
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = true,
                            Label = "About Us",
                            Order = 2,
                            Url = "/about"
                        },
                        new
                        {
                            Id = 3,
                            IsVisible = true,
                            Label = "Our Impact",
                            Order = 3,
                            Url = "/our-impact"
                        },
                        new
                        {
                            Id = 4,
                            IsVisible = true,
                            Label = "Locations",
                            Order = 4,
                            Url = "/locations"
                        },
                        new
                        {
                            Id = 5,
                            IsVisible = true,
                            Label = "Fees",
                            Order = 5,
                            Url = "/fees"
                        },
                        new
                        {
                            Id = 6,
                            IsVisible = true,
                            Label = "FAQs",
                            Order = 6,
                            Url = "/faqs"
                        },
                        new
                        {
                            Id = 7,
                            IsVisible = true,
                            Label = "News",
                            Order = 7,
                            Url = "/news"
                        },
                        new
                        {
                            Id = 8,
                            IsVisible = true,
                            Label = "Apply Now",
                            Order = 8,
                            Url = "/apply"
                        },
                        new
                        {
                            Id = 9,
                            IsVisible = true,
                            Label = "Contact Us",
                            Order = 9,
                            Url = "/contact"
                        });
                });

            modelBuilder.Entity("Diyalo.Api.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Diyalo.Api.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "siteName",
                            Value = "Diyalo"
                        },
                        new
                        {
                            Id = 2,
                            Key = "address",
                            Value = "Kathmandu, Nepal"
                        },
                        new
                        {
                            Id = 3,
                            Key = "phone",
                            Value = "+977 9800000000"
                        },
                        new
                        {
                            Id = 4,
                            Key = "email",
                            Value = "contact@diyalo.org"
                        },
                        new
                        {
                            Id = 5,
                            Key = "facebook",
                            Value = "https://facebook.com"
                        },
                        new
                        {
                            Id = 6,
                            Key = "instagram",
                            Value = "https://instagram.com"
                        },
                        new
                        {
                            Id = 7,
                            Key = "linkedin",
                            Value = "https://linkedin.com"
                        },
                        new
                        {
                            Id = 8,
                            Key = "youtube",
                            Value = "https://youtube.com"
                        },
                        new
                        {
                            Id = 9,
                            Key = "tiktok",
                            Value = "https://tiktok.com"
                        },
                        new
                        {
                            Id = 10,
                            Key = "officeHours",
                            Value = "Sun – Fri: 9am – 5pm"
                        });
                });

            modelBuilder.Entity("Diyalo.Api.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Diyalo.Api.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Diyalo.Api.Models.VolunteerProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
